version: "2"
services:
  #############################
  # bootnode
  # generate each nodes enode url
  #############################
  bootnode:
    image: hermeslin/private-chain:bootnode-1.1
    build:
      context: ./bootnode
      dockerfile: Dockerfile
    volumes:
      - ${BOOTNODE_STORE_FOLDER}:/root/store
  #############################
  # solidity
  #############################
  solidity:
    image: hermeslin/private-chain:solidity-1.0
    build:
      context: ./solidity
      dockerfile: Dockerfile
      args:
        timezone: ${TIME_ZONE}
    volumes:
      - ${SOLIDITY_STORE_FOLDER}:/root/solidity
  #############################
  # truffle
  #############################
  truffle:
    image: hermeslin/private-chain:truffle-1.0
    build:
      context: ./truffle
      dockerfile: Dockerfile
      args:
        timezone: ${TIME_ZONE}
    volumes:
      - ${TRUFFLE_STORE_FOLDER}:/root/truffle
  #############################
  # ganache-cli
  #############################
  ganache-cli:
    image: hermeslin/private-chain:ganache-cli-1.0
    build:
      context: ./ganache-cli
      dockerfile: Dockerfile
      args:
        timezone: ${TIME_ZONE}
    stop_grace_period: 30s
    stop_signal: SIGINT
    expose:
      - ${GANACHE_CLI_PORT}
    ports:
      - "${GANACHE_CLI_HOST_PORT}:${GANACHE_CLI_PORT}"
    volumes:
      - ${TRUFFLE_STORE_FOLDER}:/root/truffle
    command: ["--accounts", "${GANACHE_CLI_ACCOUNTS}", "--port", "${GANACHE_CLI_PORT}", "--networkId", "${GANACHE_CLI_NETWORK_ID}"]
  #############################
  # geth
  #############################
  geth:
    image: hermeslin/private-chain:geth-1.3
    build:
      context: ./geth
      dockerfile: Dockerfile
      args:
        timezone: ${TIME_ZONE}
    environment:
      - MACHINE_TYPE=geth
    stop_grace_period: 1m0s
    stop_signal: SIGTERM
    mem_limit: 1524m
    restart: unless-stopped
    expose:
      - ${GETH_NODE_PORT}
      - ${GETH_NODE_PORT}/udp
      - 8400
    volumes:
      - ${BOOTNODE_STORE_FOLDER}/${GETH_BOOTNODE_KEY}:/root/node.key:ro
      - ${BOOTNODE_STORE_FOLDER}/static-nodes.json:/root/static-nodes.json:ro
      - ${GENESIS_FILE}:/root/genesis.json:ro
      - ${GETH_STORE_FOLDER}:/root/store
    command: ["--networkid", "${CHIAN_ID}", "--rpc", "--rpcvhosts", "geth", "--rpcaddr", "0.0.0.0", "--rpcport", "8400", "--nodiscover"]
    #ports:
    #  - "8585:8545"
    #   - "30303:30303"
    networks:
      back-tier:
        ipv4_address: ${GETH_IP}
  #############################
  # miner
  #############################
  miner:
    image: hermeslin/private-chain:miner-1.3
    build:
      context: ./miner
      dockerfile: Dockerfile
      args:
        timezone: ${TIME_ZONE}
    environment:
      - MACHINE_TYPE=miner
      - MINER_PWD=${MINER_PWD}
    stop_grace_period: 1m0s
    stop_signal: SIGTERM
    mem_limit: 1524m
    restart: unless-stopped
    expose:
      - ${MINER_NODE_PORT}
      - ${MINER_NODE_PORT}/udp
      - 8400
    volumes:
      - ${BOOTNODE_STORE_FOLDER}/${MINER_BOOTNODE_KEY}:/root/node.key:ro
      - ${BOOTNODE_STORE_FOLDER}/static-nodes.json:/root/static-nodes.json:ro
      - ${GENESIS_FILE}:/root/genesis.json:ro
      - ${MINER_STORE_FOLDER}:/root/store
    command: ["--networkid", "${CHIAN_ID}", "--mine", "--minerthreads=1", "--rpc", "--rpcvhosts", "miner", "--rpcaddr", "0.0.0.0", "--rpcport", "8400", "--nodiscover"]
    #ports:
    #  - "8585:8545"
    #   - "30303:30303"
    networks:
      back-tier:
        ipv4_address: ${MINER_IP}
  #############################
  # monitor-view
  #############################
  monitor-view:
    image: hermeslin/private-chain:monitor-view-1.0
    build:
      context: ./monitor-view
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONITOR_VIEW_SECRET=${MONITOR_VIEW_SECRET}
    depends_on:
      - bootnode
    ports:
      - "${MONITOR_VIEW_LOCAL_PORT}:3000"
    expose:
      - 3000
    networks:
      back-tier:
  #############################
  # monitor-api-miner
  #############################
  monitor-api-miner:
    image: hermeslin/private-chain:monitor-api-1.0
    build:
      context: ./monitor-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONITOR_VIEW_SECRET=${MONITOR_VIEW_SECRET}
      - MACHINE_TYPE=miner
    depends_on:
      - miner
    networks:
      back-tier:
  #############################
  # monitor-api-geth
  #############################
  monitor-api-geth:
    image: hermeslin/private-chain:monitor-api-1.0
    build:
      context: ./monitor-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONITOR_VIEW_SECRET=${MONITOR_VIEW_SECRET}
      - MACHINE_TYPE=geth
    depends_on:
      - geth
    networks:
      back-tier:
networks:
  back-tier:
    driver: bridge
    ipam:
      config:
      -
        subnet: ${SUBNET}